### ISSUE TITLE
rewrite-clj.node/sexpr does not work

### ISSUE THREAD

**Issue by kennyjwilli** [clj-commons/rewrite-cljs#13]
As discussed here https://github.com/weavejester/cljfmt/issues/106, `rewrite-clj.node/sexpr` does not work which is used internally by the zipper. This breaks cljfmt.

**Comment by PEZ** [comment]
Is something happing with this?

**Comment by lread** [comment]
This issue has been addressed in https://github.com/clj-commons/rewrite-clj
