### ISSUE TITLE
Revisit Namespaced keywords

### ISSUE THREAD

**Issue by SevereOverfl0w** [clj-commons/rewrite-cljs#14]
I think this is going to be a more & more pressing issue as namespaced keywords are now the recommended way of doing business.

What is the blocker to enabling them?

**Comment by SevereOverfl0w** [comment]
To be clear, I'm interested in getting them working, and can put in some effort in order to do so.

**Comment by PEZ** [comment]
Is this issue getting any attention?

**Comment by lread** [comment]
Hiya, I am [currently fleshing out support for namespaced maps in rewrite-clj](https://github.com/xsc/rewrite-clj/issues/54). I'll come back here and have a look at this issue when I'm done over there.

**Comment by lread** [comment]
Until someone finds some time to have a look at [my pull request over at rewrite-clj](https://github.com/xsc/rewrite-clj/pull/71), I have been playing locally on my computer with adding namespaced map support to rewrite-cljs.  

It all looks good with the exception of `sepxr` support. Unless someone has a better idea, I think I'll take the [same approach as was taken with rewrite-cljs keywords](https://github.com/rundis/rewrite-cljs/blob/5ed0980d4fc65ba00780deadb3cf245d742bfeb9/src/rewrite_clj/node/keyword.cljs#L16) and simply throw an exception.

**Comment by lread** [comment]
This issue has been addressed in https://github.com/clj-commons/rewrite-clj
