### ISSUE TITLE
Features are lagging behind rewrite-clj

### ISSUE THREAD

**Issue by lread** [clj-commons/rewrite-cljs#19]
Because rewrite-cljs has not been actively maintained, its features have lagged behind rewrite-clj.

**Comment by lread** [comment]
Some initial notes
1. To avoid feature lag in the future, it is interesting to explore making this a cljc project. 
1. Notable differences between rewrite-clj and rewrite-cljs
   1. There are ClojureScript specific optimizations in rewrite-cljs. [Rundis wrote up some good notes](http://rundis.github.io/blog/2015/clojurescript_performance_tuning.html). These optimizations were done in 2015 and I wonder which ones are still relevant today. I will have to research more here. Perhaps add some benchmarks. My initial stab will likely favour rewrite-clj code over optimized rewrite-cljs code.
   1. Supporting namespaced map variables will be a bit more challenging in rewrite-cljs. There is no language support for querying namespaces at runtime in ClojureScript.
   1. rewrite-cljs and rewrite-clj both added positional support, but in different ways. I will use rewrite-clj's implementation.
   1. rewrite-clj uses a version of potemkin's `import-vars` to bring functions and macros into the api layer. This seems elegant to me. I see a path to doing this for rewrite-cljs for functions, but have to learn if I can do it for macros as well.
1. To understand
   1. Why do some rewrite-cljs namespaces have a z tacked onto the end? For example `rewrite-clj.zip.editz`, `rewrite-clj.zip.findz`, `rewrite-clj.zip.removez`, `rewrite-clj.zip.seqz`. It looks like the intent was to avoid name collisions, but I don't get it yet. 
      - A: In ClojureScript vars can clash with namespaces. This naming scheme was adopted in rewrite-cljs to avoid these collisions
   1. What about Clojure/ClojureScript language differences? How does rewrite-cljs deal with Clojure numbers (ratios, for example).

I am going to work away at the above, but any concerns, clarifications and ideas are most welcome.

**Comment by lread** [comment]
Let's assume I make this a cljc project - this means I am affecting Clojure and ClojureScript users.

To solve the namespace clash (item 3i), I could either adopt the the current rewrite-cljs naming (eg. findz etc) or move all internal code under an `internal` namespace.  The latter is more drastic, but does add the benefit of making it plain to users when they are making use of internal code.  

Both options do not break what I interpret to the the public API. I expect my interpretation of the public API is correct, but there is a chance I have misunderstood what was intended by the original author.

I was going to proceed with the internal namespace approach but noticed many code bases are using what I understand to be the internal api. For this reason, I am going to avoid breaking both internal and external apis for rewrite-clj and rewrite-cljs. 

Comments and objections are most welcome.

**Comment by lread** [comment]
I've looked into differences in positional support (item 2iii).  Here is my current understanding (corrections always welcome).

rewrite-cljs uses the positional support offered by the clojure tools reader.  It looks at the `:row` `:col` `:end-row` and `:end-col` metadata the reader provides.  The rewrite-cljs API accepts position as map, for example: `{:row 3 :col 10}`. Because the positions come from the reader, positions do not adapt when changes are made via the zipper.  rewrite-cljs exposes a couple of positional find functions and makes use of these in its paredit API.

rewrite-clj implements full position tracking through a custom zipper.  Position tracking is enabled at time of zipper creation. Calling `position` on zloc returns a row col vector, for example `[3 10]`, for start position of current node.  Position is updated with changes affected by zipper. 

Options:
1. Leave rewrite-cljs positional and paredit support as is as a legacy feature as cljs only. 
1. Remove rewrite-cljs positional support and 3 functions in paredit that make use of this support. Expose remainder to both cljs and clc. Some potential breakage for cljs users.
1. Remove rewrite-cljs positional and paredit support entirely. Breaks cljs, clj unaffected.
1. Upgrade rewrite-cljs positional support to rewrite-clj version. rewrite-cljs internal usage of `:end-row` and `:end-col` complicates this task.  Would likely still accept `{:row r :col c}` for legacy clients but would encourage `[r c]` vector to match rewrite-clj's implementation choice. Note that using position tracking may have an impact on performance.  
   * Breaks cljs in that it now must create zippers with `:track-position?` if positional features are used and, in this case, can no longer use clojure.zip.  
   * clj gets new paredit and find functions.

If I knew how many folks are using rewrite-cljs paredit and position support, this would affect my approach. I have explored option 4, and in my tests, it seems workable.

Feedback is most welcome.
A search on github shows that https://github.com/clojure-vim/clj-refactor.nvim makes use of paredit - @snoe do you have an opinion on this?

**Comment by snoe** [comment]
my apologies, this is a bit of a quick reply. 

I've actually been pseudo-porting clj-refactor.nvim to rewrite-clj for snoe/clojure-lsp 

It would be nice to have a common cljc codebase to work with and I feel that rewrite-cljs had a few extra workarounds I had to do to keep my zipper in the "right" position after operations.

For both plugins, I heavily use positioning since most operations feeding back to vim need to provide char ranges to change.

My understanding of rewrite-cljs is that it was always supposed to be a temporary library until cljc matured  and rewrite-clj could merge it in. So in my opinion, while I've very much appreciated and benefited by the work of both libraries, it would be nice if there was just one rewrite library with a single API

**Comment by lread** [comment]
Hi @snoe, thanks for the reply. The original authors of rewrite-clj and rewrite-cljs did talk at one time about a merge, but neither had the time. Hopefully, my little efforts here will soon bear some fruit.

As for positional (row, col) support, you will have to make a few changes, but my initial tests look promising.

**Comment by lread** [comment]
I  looked into namespaced map support today.

To test my research, I merge [my pull request from rewrite-clj](https://github.com/xsc/rewrite-clj/pull/71) into my rewrite-cljs workspace.

I looked into Clojure tools reader. It supports ClojureScript auto resolve alias namespaced maps with its `*alias-map*` binding.  I think I will follow suit.

Reminder: auto-resolve alias namespaced maps specify a namespace alias in the prefix, for example `#::node{:x 1, :y 1}`. 

So, when used as a ClojureScript library, it won't be up to the new rewrite-cljs to parse out namespace aliases for you, but you can provide them via the `*alias-map*` binding.  And..
1. this should only be necessary if you are parsing an auto-resolve alias namespaced map AND you need its sexpr. 
1. remember, this is only an issue when using rewrite-cljs as a ClojureScript library. ClojureScript lacks Clojure's ability to parse out namespace aliases. When using the upcoming rewrite-cljs as a Clojure library, namespace aliases will be parsed out automatically. That said, you will be free to override namespace aliases with the `*alias-map*` from Clojure should you need/want to.

Thoughts and concerns are, as always, most welcome.

**Comment by lread** [comment]
While the above conversation above is stale, this issue has been addressed in https://github.com/clj-commons/rewrite-clj
