### ISSUE TITLE
Usage of undeclared variables

### ISSUE THREAD

**Issue by comamitc** [clj-commons/rewrite-cljs#4]
I haven't looked into this at all but what I noticed was that on `master` and when depending on `rewrite-cljs` in another project, I get the following compiler warnings:
- [ ] WARNING: Use of undeclared Var rewrite-clj.node/raw-meta-node at line 74 out/rewrite_clj/parser/core.cljs
- [ ] WARNING: Use of undeclared Var rewrite-clj.node/length at line 49 out/rewrite_clj/zip/base.cljs
- [ ] WARNING: Use of undeclared Var rewrite-clj.node/length at line 49 out/rewrite_clj/zip/base.cljs
- [ ] WARNING: Use of undeclared Var rewrite-clj.node/value at line 55 out/rewrite_clj/zip/base.cljs

**Comment by rundis** [comment]
fixed in master
