### ISSUE TITLE
Regular expressions parsed incorrectly

### ISSUE THREAD

**Issue by weavejester** [clj-commons/rewrite-cljs#7]
There are some regular expressions that are not parsed correctly, such as:

``` clojure
(n/string (p/parse-string "(re-find #\"(?i)RUN\" s)"))
=> "(re-find #\"RUN\" s)"
```

This bug doesn't occur in rewrite-clj, but does occur in rewrite-cljs.

**Comment by rundis** [comment]
hmm weird. It seems this is caused by how re-pattern behaves in ClojureScript, which is somewhat surprising/unfortunate.

**Comment by weavejester** [comment]
Thanks for the fix!

**Comment by weavejester** [comment]
Any chance of a release with this fix?

**Comment by rundis** [comment]
Done !

**Comment by weavejester** [comment]
Thanks!
