### ISSUE TITLE
Support reader conditionals.

### ISSUE THREAD

**Issue by carrete** [clj-commons/rewrite-cljs#8]
I [assume](https://www.youtube.com/watch?v=LfvTwv5o1Qs) that because this [just landed in xsc/rewrite-clj](https://github.com/xsc/rewrite-clj/blob/master/CHANGES.md#052) that this doesn't exist here. Required by https://github.com/weavejester/cljfmt/issues/59. My hope is that this is just a merge or copy-and-paste into this repository.

**Comment by rundis** [comment]
Should be fixed now. Mostly a copy paste fix yeah.

**Comment by rundis** [comment]
Oh and 0.4.2 released on clojars. ping @weavejester

**Comment by carrete** [comment]
> Oh and 0.4.2 released on clojars.

Awesome! Thanks for the quick turnaround!
